name: app_movie
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    dio: ^5.9.0
    flutter_bloc: ^9.1.1
    hive: ^2.2.3
    connectivity_plus: ^5.0.2
    get_it: ^8.2.0
    flutter_dotenv: ^6.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
